spring.application.name=bookshop
spring.datasource.url=jdbc:postgresql://localhost:5432/chatchit
spring.datasource.username=postgres
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
server.servlet.context-path=/api
schedule.jwtSecret = mongdoikhongbuonkhongtuicuocsongvolovonghi32charactersabcxyzt12345
schedule.jwtExpirationMs = 86400000
email.expirationMin = 1440
spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.security.oauth2.client.registration.google.client-id=255068981159-ctddhv9i7g4pnluk5810bq5f7gvhqmnt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lam20052802@gmail.com
spring.mail.password=zzfd cjas iwcx pxbz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000




